/* Regenerate only the selected Lucide icon data from an installed package. */
const fs = require('node:fs');
const path = require('node:path');
const packageRoot = process.argv[2] || path.dirname(require.resolve('lucide/package.json'));
const lib = require(path.join(packageRoot, 'dist/cjs/lucide.js'));
const names = ['ArrowUpRight', 'ArrowDownRight', 'ArrowRight', 'ArrowDown', 'ArrowUp', 'ArrowDownUp', 'Check', 'CodeXml', 'Copy', 'CopyCheck', 'Download', 'FileCheck2', 'FileText', 'Files', 'Folder', 'FolderOpen', 'Github', 'HardDrive', 'Menu', 'X', 'Pause', 'Play', 'Plus', 'Search', 'RotateCcw', 'Table2', 'Sheet', 'ShieldCheck', 'ScanLine', 'TriangleAlert', 'Terminal', 'Package', 'Braces', 'Eye', 'Printer', 'Layers', 'FileSpreadsheet', 'Rows3', 'Type', 'PanelsTopLeft', 'ScanText', 'NotebookPen', 'UserCheck', 'PackageCheck', 'Calculator', 'ChevronLeft', 'ChevronRight', 'ZoomIn'];
const kebab = value => value.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([a-zA-Z])(\d+)/g, '$1-$2').toLowerCase();
const icons = Object.fromEntries(names.map(name => {
  const sourceName = name === 'Github' ? 'GitFork' : name;
  if (!Array.isArray(lib[sourceName])) throw new Error(`Missing Lucide icon: ${sourceName}`);
  return [kebab(name), lib[sourceName]];
}));
const destination = path.resolve(__dirname, '../assets');
fs.mkdirSync(destination, { recursive: true });
fs.writeFileSync(path.join(destination, 'icons.js'), `/* Lucide ${require(path.join(packageRoot, 'package.json')).version}; ISC license in LICENSE-lucide. Generated by scripts/vendor-icons.cjs. */\nwindow.InvoiceHubIcons = ${JSON.stringify(icons)};\n`);
fs.copyFileSync(path.join(packageRoot, 'LICENSE'), path.join(destination, 'LICENSE-lucide'));
console.log(`Vendored ${names.length} Lucide icons.`);
